console.log("# Load time")
console.time("picomatch")
export var pm = require("..")
console.timeEnd("picomatch")
console.time("minimatch")
export var mm = require("minimatch")
console.timeEnd("minimatch")
console.log()
